#!/bin/bash
export TERM="xterm-256color"
echo $@

if [[ ! $1 ]]; then
    gvim -geometry 500x500 -f --servername GVIM
	#mlterm -geometry 500x500 --sb=false -e vi -f --servername VI
fi

if [[ $1 ]]; then
	#gvim -f --servername GVIM --remote-tab "${@}" 
    gvim -geometry 500x500 -f --servername GVIM --remote "${@}" 
	#mlterm -geometry 500x500 --sb=false -e vi -f --servername VI --remote "${@}"
fi

wmctrl -a gvim 
